Repository CM20314-Group-7/rental-review, pull requests merged in 2024-02, with the labels that each got.

#31 Handle Property Page Not Found
  app/properties/[id]/page.tsx
Labels: minor

#32 Revert "RRS-150 New User Profiles"
  supabase.types.ts
  supabase/migrations/20240218001951_new_user_profiles.sql
Labels: bug

#34 Update workflow names
  .github/workflows/database-tests.yml
  .github/workflows/frontend-tests.yml
  .github/workflows/generate-types.yml
  .github/workflows/production.yml
Labels: documentation, minor

#33 RRS-150 New User Profiles V2
  .env.example
  .env.local.example
  .gitignore
  package-lock.json
  package.json
  playwright-tests/auth.setup.ts
  playwright-tests/helpers.ts
  playwright-tests/supabase-user-tests.spec.ts
  playwright.config.ts
  supabase.types.ts
  supabase/migrations/20240222092851_new_user_profiles_v2.sql
  supabase/seed.sql
Labels: bug, enhancement, dependencies

#27 RRS-108 Create Landlord Profile Page
  app/profiles/[landlordId]/page.tsx
  app/profiles/page.tsx
  supabase.types.ts
  supabase/migrations/20240222135454_move_landlord_details_to_private_table.sql
Labels: enhancement

#39 Setup color scheme configuration
  app/globals.css
  tailwind.config.js
Labels: minor

#37 RRS-108 create landlord profile page
  .gitignore
  playwright-tests/landlord-page-tests.spec.ts
  supabase/migrations/20240224001029_added_policy_for_landlord_public.sql
  supabase/seed.sql
Labels: enhancement

#43 property details redesign
  app/properties/[id]/page.tsx
  package-lock.json
Labels: enhancement

#41 New Colours
  app/globals.css
Labels: minor

#44 Dynamic users in tests
  playwright-tests/helpers.ts
  playwright-tests/landlord-page-tests.spec.ts
  playwright-tests/supabase-user-tests.spec.ts
Labels: minor

#36 Landing page redesign
  app/layout.tsx
  app/opengraph-image.png
  app/page.tsx
  app/twitter-image.png
  components/AuthButton.tsx
  components/Code.tsx
  components/ConnectSupabaseSteps.tsx
  components/DeployButton.tsx
  components/Footer.tsx
  components/Footer/DarkModeToggle.tsx
  components/Footer/Footer.tsx
  components/Header.tsx
  components/Header/AuthButton.tsx
  components/Header/HomeButton.tsx
  components/Header/NavBar.tsx
  components/Header/NavLink.tsx
  components/Header/UserManagementButton.tsx
  components/Header/actions.ts
  components/HomeButton.tsx
  components/NavBar.tsx
  components/NextLogo.tsx
  components/SearchButton.tsx
  components/SignUpUserSteps.tsx
  components/Step.tsx
  components/SupabaseLogo.tsx
Labels: minor

#38 Property search redesign
  app/properties/page.tsx
Labels: minor

#46 Login redesign and redirect
  app/login/actions.ts
  app/login/forms.tsx
  app/login/page.tsx
Labels: minor
